#!/usr/bin/env bash

if
  [[ -s "/home/evekin13/.rvm/gems/ruby-2.4.10/environment" ]]
then
  source "/home/evekin13/.rvm/gems/ruby-2.4.10/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/evekin13/.rvm/gems/ruby-2.4.10/environment'" >&2
  exit 1
fi
