#!/usr/bin/env bash

if
  [[ -s "/home/evekin13/.rvm/rubies/ruby-2.4.10/lib/ruby/gems/2.4.0/environment" ]]
then
  source "/home/evekin13/.rvm/rubies/ruby-2.4.10/lib/ruby/gems/2.4.0/environment"
  exec ruby_executable_hooks "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/evekin13/.rvm/rubies/ruby-2.4.10/lib/ruby/gems/2.4.0/environment'" >&2
  exit 1
fi
